# Generated by Django 3.2.8 on 2021-11-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211121_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='title',
        ),
    ]
