# Generated by Django 3.2.8 on 2021-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211122_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
    ]
